services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Importer\Service\:
    resource: "services/*"
    autowire: false

  YesWiki\Importer\Service\ImporterManager:
    autowire: true
